Numpy stands for Numerical Python. Numpy is a general purpose array-processing package. It provides with high performance multi-dimensional array objects and tools for working with these arrays.

Numpy is fundamental package for scientific computing with Python.

Numy provides us with following 

    i) a powerful N-dimensional array object
    ii) sophisticated (broadcasting) functions
    iii) tools for integrating C/C++ and Fortran code
    iv) useful linear algebra, Fourier transform, and random number capabilities

Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data. Arbitrary data-types can be defined. This allows NumPy to seamlessly and speedily integrate with a wide variety of databases.

There are several important differences between NumPy arrays and the standard Python sequences:
    
    a) NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). If user try to change the size of ndarray, it will create new ndarray and delete the original.
    
    b) Numpy array all elements are to be same data type and thus have same memory size for all elements. This has one exception, where Numpy array can have array of objects thereby allowing for arrays to have different sized elements.
    
    c) NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data.

# The Basics

Numpy arrays are all multi-dimensional arryas with homogeneous data types i.e., all the elements in the array are of same data types which are indexed by tuple of positive numbers.

In Numpy, dimensions are called as 'axes'.

NumPy’s array class is called ndarray. It is also known by the alias array.

Note: numpy.array is not the same as the Standard Python Library class array.array, which only handles one-dimensional arrays and offers less functionality.

# ndarray

ndarray object is the core of Numpy package. This encapsulates n-dimensional arrays of homogeneous data types i.e., all the elements in the array are of same data types. 

## Below shown are some important attributes if ndarray object.

### ndarray.ndim

Gives the number of axes i.e., dimensions of the array.

### ndarray.size

The total number of elements of the array. This is equal to the product of the elements of shape.

### ndarray.dtype

An object describing the type of the elements in the array. One can create or specify dtype’s using standard Python types. Additionally NumPy provides types of its own. numpy.int32, numpy.int16, and numpy.float64 are some examples.

### ndarray.itemsize

The size in bytes of each element of the array. For example, an array of elements of type float64 has itemsize 8 (=64/8), while one of type complex32 has itemsize 4 (=32/8). It is equivalent to ndarray.dtype.itemsize.

### ndarray.data

The buffer containing the actual elements of the array. Normally, we won’t need to use this attribute because we will access the elements in an array using indexing facilities.

# Exercise 1 - Calculate BMI using regular lists and Numpy Array.

### using regular lists

In [4]:
ht = [1.71, 1.58, 1.51, 1.73, 1.92]

In [5]:
wt = [65.9, 58.8, 66.8, 83.4, 68.7]

In [6]:
### BMI = weight / height ** 2
BMI = wt / ht ** 2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

### using numpy arrays

In [7]:
import numpy as np

In [8]:
np_ht = np.array(ht)

In [12]:
type(np_ht)

numpy.ndarray

In [9]:
np_ht

array([1.71, 1.58, 1.51, 1.73, 1.92])

In [10]:
np_wt = np.array(wt)

In [13]:
type(np_wt)

numpy.ndarray

In [11]:
np_wt

array([65.9, 58.8, 66.8, 83.4, 68.7])

In [14]:
BMI = np_wt / np_ht ** 2

In [15]:
BMI

array([22.53684894, 23.55391764, 29.29696066, 27.86594941, 18.63606771])

In [16]:
BMI[1]

23.553917641403615

In [17]:
BMI[1 : 3]

array([23.55391764, 29.29696066])

In [18]:
BMI[BMI > 28]

array([29.29696066])

If there are differnt data types in numpy array all the elements are typecasted to possible data type.

# Exercise 2 - Try numpy array with different data types

In [19]:
a_list = [1, 2, 3, 4, 5.23]

In [20]:
a_np = np.array(a_list)

In [22]:
a_list

[1, 2, 3, 4, 5.23]

In [23]:
a_np

array([1.  , 2.  , 3.  , 4.  , 5.23])

In [24]:
b_list = [1, 2, 3, 4, 'Hai']

In [25]:
b_np = np.array(b_list)

In [26]:
b_list

[1, 2, 3, 4, 'Hai']

In [27]:
b_np

array(['1', '2', '3', '4', 'Hai'], dtype='<U11')

In [28]:
c_list = [1, 2, 3, {1:'one'}, 5.23]

In [29]:
c_np = np.array(c_list)

In [31]:
c_list

[1, 2, 3, {1: 'one'}, 5.23]

In [30]:
c_np

array([1, 2, 3, {1: 'one'}, 5.23], dtype=object)

# Exercise 3 - arange and reshape

In [39]:
a = np.arange(6)

In [40]:
a

array([0, 1, 2, 3, 4, 5])

In [64]:
a.ndim

1

In [41]:
b = np.arange(12).reshape(4, 3)

In [42]:
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [65]:
b.ndim

2

In [43]:
c = np.arange(12).reshape(3, 4)

In [44]:
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [67]:
c.ndim

2

In [45]:
d = np.arange(12).reshape(2, 2, 3)

In [46]:
d

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [68]:
d.ndim

3

In [49]:
e = np.arange(28).reshape(14, 2)

In [50]:
e

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27]])

In [69]:
e.ndim

2

In [51]:
f = np.arange(28).reshape(7, 2, 2)

In [52]:
f

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27]]])

In [70]:
f.ndim

3

In [56]:
g = np.arange(24).reshape(6, 4)

In [57]:
g

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [71]:
g.ndim

2

In [58]:
h = np.arange(24).reshape(4, 6)

In [59]:
h

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [72]:
h.ndim

2

In [60]:
i = np.arange(24).reshape(2, 3, 4)

In [61]:
i

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [73]:
i.ndim

3

In [62]:
j = np.arange(24).reshape(2, 3, 2, 2)

In [63]:
j

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11]]],


       [[[12, 13],
         [14, 15]],

        [[16, 17],
         [18, 19]],

        [[20, 21],
         [22, 23]]]])

In [74]:
j.ndim

4

# Exercise 4 - Numpy array occupies less memory

In [77]:
a_list = list(range(13))

In [78]:
a_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [79]:
a_np = np.array(a_list)

In [80]:
a_np

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [83]:
import sys

In [84]:
sys.getsizeof(a_list)

224

In [85]:
sys.getsizeof(a_np)

148

In [86]:
l= [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [88]:
l

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [87]:
n = np.array(l)

In [89]:
n

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [90]:
sys.getsizeof(l)

160

In [91]:
sys.getsizeof(n)

144

# Exercise 5 - Working with 2d numpy arrays

In [92]:
np_2d_array = np.array([[1.71, 1.58, 1.51, 1.73, 1.92], [65.9, 58.8, 66.8, 83.4, 68.7]])

In [94]:
type(np_2d_array)

numpy.ndarray

In [93]:
np_2d_array

array([[ 1.71,  1.58,  1.51,  1.73,  1.92],
       [65.9 , 58.8 , 66.8 , 83.4 , 68.7 ]])

In [95]:
np_2d_array.shape

(2, 5)

In [96]:
np_2d_array[1]

array([65.9, 58.8, 66.8, 83.4, 68.7])

In [97]:
np_2d_array[0]

array([1.71, 1.58, 1.51, 1.73, 1.92])

In [98]:
np_2d_array[0][2]

1.51

In [100]:
np_2d_array[1][0]

65.9

In [101]:
np_2d_array[0, 2]

1.51

In [102]:
np_2d_array[1, 3]

83.4

In [103]:
np_2d_array[:, :2]

array([[ 1.71,  1.58],
       [65.9 , 58.8 ]])

In [104]:
np_2d_array[1, :]

array([65.9, 58.8, 66.8, 83.4, 68.7])

In [106]:
np_2d_array[0, :]

array([1.71, 1.58, 1.51, 1.73, 1.92])

In [107]:
np_2d_array[:, 1]

array([ 1.58, 58.8 ])

# Exercise 6 - Working with basic statistics

In [108]:
x = [1, 4, 8, 10, 12]

In [109]:
np.mean(x)

7.0

In [110]:
np.median(x)

8.0

In [112]:
np.std(x)

4.0